### ISSUE TITLE
Refactoring with nan to work with node.js 0.12 and io.js

### ISSUE THREAD

**Issue by adrai** [thomaschaaf/node-ftdi#11]

**Comment by thomaschaaf** [comment]
I would also love to see a version which works with 0.12. Can you give me some pointers then I would try to debug.

**Comment by adrai** [comment]
Unfortunately it's a complete rewrite with the help of the nan library...



Il giorno 20-feb-2015, alle ore 19:24, Thomas Schaaf <notifications@github.com<mailto:notifications@github.com>> ha scritto:


I would also love to see a version which works with 0.12. Can you give me some pointers then I would try to debug.

-

**Comment by thomaschaaf** [comment]
What is the status with the nan branch? How can I help? I would love to support you if I can.

**Comment by adrai** [comment]
I assume this is an old "non-really-working" state...
But if you have some C++ skills and know-how for the nan stuff... feel free to create a pull request ;-)

**Comment by thomaschaaf** [comment]
I don't have any c++ skills :D but I tried my hand at trying to get it to work on 0.12..
I am now able to find the usb relay.. but I don't think the "write" command is being executed. I tried adding "cout" output to debug if the functions are being called but am getting no output. Do you have any idea or could you test it and check if your devices work?

See my pull request #13

**Comment by adrai** [comment]
Ok, the recommendation of other is to not use the nan branch... it already was corrupted...
If you really want to try something start from the master branch...

**Comment by thomaschaaf** [comment]
:frowning: I did not understand that from your comment 3 days ago... and thought that was a good starting point

I actually got the code to work with a little hack which maybe you can explain or point me in the right direction.
```
nvm use 0.10
cd node-ftdi

git checkout nan
node-gyp rebuild
node test/testScript.js
-> no on("data") event fired and nothing sent to the device

git checkout master
node-gyp rebuild
node test/testScript.js
-> works

git checkout nan
node-gyp rebuild
node test/testScript.js
-> works
```
Could some driver initialization not be happening? If I unplug the device it doesnt work again..

**Comment by adrai** [comment]
I cloned your fork and try to rebuild but:

./src/nan_new.h:194:11: fatal error: 'nan_implementation_pre_12_inl.h' file not found
# include "nan_implementation_pre_12_inl.h"

**Comment by adrai** [comment]
I copied locally https://github.com/rvagg/nan/blob/master/nan_implementation_pre_12_inl.h file

**Comment by adrai** [comment]
ok, I checked it personally...
I tested it with an in-house device product and there I get:
undefined:0
TypeError: undefined is not a function
findallmethodfindallworkerfindallmethodfindallmethodfindallmethodfindallworkerfindallworkerSegmentation fault: 11

sorry I have no idea....

**Comment by thomaschaaf** [comment]
Bitbang was not implemented :) Check now its working for us. I will check in the future as it will be used multiple times daily.

**Comment by adrai** [comment]
same as before.... :-(
the in-house device product does not use bitbang...

**Comment by adrai** [comment]
I will escalate the node.js 0.12 support in the org... so they will have 2 possibilities: 1) make a proper node 0.12 support or 2) give the ownership to some one else...

**Comment by adrai** [comment]
Tomorrow I will have some time to investigate more....

**Comment by adrai** [comment]
May you adapt your pull request to integrate nan like https://github.com/voodootikigod/node-serialport ?

**Comment by adrai** [comment]
Ok, I tested with your fork... It seams to work now... I have adapted the devicestack...

**Comment by NPellet** [comment]
Hey ! Any news on the version with 0.12 ? Is there something working ?

**Comment by adrai** [comment]
Waiting for response of @thomasschaaf

**Comment by thomaschaaf** [comment]
Hmm I integrated nan the "correct" way now but it seems to be lots of work to get my branch to merge into master without a merge conflict.. I did go back and manually put every change since the nan split off into my branch (install.sh, bitbang and Readme). I also made my version 1.2.0 as the nan change may not work for everyone.
